import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://zjheeurzlgcpaxhvibiu.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqaGVldXJ6bGdjcGF4aHZpYml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk2NDUyMjUsImV4cCI6MjA0NTIyMTIyNX0.EjXCRcLPiLEq9VbWxfL6d6cvQsWGQQP0l1aRyuHArDw')